set_property PACKAGE_PIN V17 [get_ports {in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[0]}]
set_property PACKAGE_PIN V16 [get_ports {in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {in[1]}]
set_property PACKAGE_PIN W16 [get_ports {sel}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel}]
set_property PACKAGE_PIN U16 [get_ports {out}]
set_property IOSTANDARD LVCMOS33 [get_ports {out}]